name: flutter_starter_kit
description: "A starter kit Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.4.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # localization:
  easy_localization: ^3.0.7

  # fonts:
  google_fonts: ^6.2.1

  # loader:
  shimmer: ^3.0.0

  # image:
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.16

  # navigation:
  go_router: ^14.6.0

  # animations:
  lottie: ^3.2.0

  # local storage:
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.4

  # state management:
  provider: ^6.1.2

  # networking
  dio: ^5.5.0
  retrofit: ^4.4.0

  # dependency injection
  get_it: ^8.0.3

  # Logging & Crash Reporting
  logger: ^2.0.2
  sentry_flutter: ^7.13.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  retrofit_generator: ^8.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/animations/
    - assets/icons/
    - assets/images/
  generate: true
